use crate::math::{Vec3f, Vec3s};
use crate::types::{ObjectId, SurfaceId};

/// Faithful Rust-side carrier for the original SM64 MarioState gameplay data.
///
/// Pointer fields from the C decomp are represented by stable IDs or deferred
/// integration handles. This keeps the simulation cloneable while preserving
/// the original state-machine shape and field semantics.
#[derive(Clone, Debug, PartialEq)]
pub struct MarioState {
    pub unk00: u16,
    pub input: u16,
    pub flags: u32,
    pub particle_flags: u32,
    pub action: u32,
    pub prev_action: u32,
    pub terrain_sound_addend: u32,
    pub action_state: u16,
    pub action_timer: u16,
    pub action_arg: u32,
    pub intended_mag: f32,
    pub intended_yaw: i16,
    pub invinc_timer: i16,
    pub frames_since_a: u8,
    pub frames_since_b: u8,
    pub wall_kick_timer: u8,
    pub double_jump_timer: u8,
    pub face_angle: Vec3s,
    pub angle_vel: Vec3s,
    pub slide_yaw: i16,
    pub twirl_yaw: i16,
    pub pos: Vec3f,
    pub vel: Vec3f,
    pub forward_vel: f32,
    pub slide_vel_x: f32,
    pub slide_vel_z: f32,
    pub wall: Option<SurfaceId>,
    pub ceil: Option<SurfaceId>,
    pub floor: Option<SurfaceId>,
    pub ceil_height: f32,
    pub floor_height: f32,
    pub floor_angle: i16,
    pub water_level: i16,
    /// Area terrain type mirrored from the original Area pointer.
    pub terrain_type: i16,
    pub interact_obj: Option<ObjectId>,
    pub held_obj: Option<ObjectId>,
    pub used_obj: Option<ObjectId>,
    pub ridden_obj: Option<ObjectId>,
    pub mario_obj: Option<ObjectId>,
    pub collided_obj_interact_types: u32,
    pub num_coins: i16,
    pub num_stars: i16,
    pub num_keys: i8,
    pub num_lives: i8,
    pub health: i16,
    pub unk_b0: i16,
    pub hurt_counter: u8,
    pub heal_counter: u8,
    pub squish_timer: u8,
    pub fade_warp_opacity: u8,
    pub cap_timer: u16,
    pub prev_num_stars_for_dialog: i16,
    pub peak_height: f32,
    pub quicksand_depth: f32,
    pub getting_blown_gravity: f32,
}

impl Default for MarioState {
    fn default() -> Self {
        Self {
            unk00: 0,
            input: 0,
            flags: 0,
            particle_flags: 0,
            action: 0,
            prev_action: 0,
            terrain_sound_addend: 0,
            action_state: 0,
            action_timer: 0,
            action_arg: 0,
            intended_mag: 0.0,
            intended_yaw: 0,
            invinc_timer: 0,
            frames_since_a: 0,
            frames_since_b: 0,
            wall_kick_timer: 0,
            double_jump_timer: 0,
            face_angle: [0; 3],
            angle_vel: [0; 3],
            slide_yaw: 0,
            twirl_yaw: 0,
            pos: [0.0; 3],
            vel: [0.0; 3],
            forward_vel: 0.0,
            slide_vel_x: 0.0,
            slide_vel_z: 0.0,
            wall: None,
            ceil: None,
            floor: None,
            ceil_height: 0.0,
            floor_height: 0.0,
            floor_angle: 0,
            water_level: 0,
            terrain_type: crate::TERRAIN_GRASS as i16,
            interact_obj: None,
            held_obj: None,
            used_obj: None,
            ridden_obj: None,
            mario_obj: None,
            collided_obj_interact_types: 0,
            num_coins: 0,
            num_stars: 0,
            num_keys: 0,
            num_lives: 4,
            health: 0x880,
            unk_b0: 0,
            hurt_counter: 0,
            heal_counter: 0,
            squish_timer: 0,
            fade_warp_opacity: 0,
            cap_timer: 0,
            prev_num_stars_for_dialog: 0,
            peak_height: 0.0,
            quicksand_depth: 0.0,
            getting_blown_gravity: 0.0,
        }
    }
}
